New feature project popup
shuhad786/My-portfolio-website pull request #7
Opened 2022-09-07 10:11 UTC by shuhad786

- Updated the Project-popup.js to enable the popup window through JS objects.
- Updated the HTML classes buttons and created a new section to store popup functions.
- Updated the CSS to style the popup window according to the Figma template.
- Updated the README.md to include the new framework and technologies.

2022-09-07 13:25 UTC, aimemalaika requested changes
Hi @shuhad786, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 13:25 UTC, aimemalaika commented on index.html
> +      <button type="button" onclick="" class="Mproject-button-4">See Project</button>
- [ ] Kindly populate the list of project dynamically using javascript

2022-09-07 13:25 UTC, aimemalaika commented on Project-popup.js
> +
- [ ] When you click on see project kindly populate the popup with the content of the selected project

2022-09-08 13:34 UTC, Munsa1 approved these changes
Hi @shuhad786, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-08 14:13 UTC, merged